# Generated by Django 4.1.4 on 2022-12-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=100)),
                ('miesiac_urodzenia', models.CharField(choices=[('ST', 'Styczeń'), ('LU', 'Luty'), ('MA', 'Marzec'), ('KW', 'Kwiecień'), ('MJ', 'Maj'), ('CZ', 'Czerwiec'), ('LI', 'Lipiec'), ('SI', 'Sierpień'), ('WR', 'Wrzesień'), ('PA', 'Październik'), ('LS', 'Listopad'), ('GR', 'Grudzień')], default='ST', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
