# Generated by Django 4.1.4 on 2022-12-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('1', 'Aktywna'), ('2', 'Nieaktywna')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('1', 'Wstawiony'), ('2', 'Niewstawiony')], default=2, max_length=2),
        ),
    ]
